#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8886/eureka
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true
#server:
#  port: 7970
#spring:
#  application:
#    name: tx-manager
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root
#    url: jdbc:mysql://127.0.0.1:3306/tx-manager?characterEncoding=UTF-8
#    username: 12345678
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#  redis:
#    host: localhost
#    password: ''
#    port: 6379
#tx-lcn:
#  logger:
#    enabled: true
#  manager:
#    concurrent-level: 128
#    dtx-time: 10000
#    heart-time: 12000
#    host: localhost
#    port: 8070
