server:
  port: 8889

spring:
  application:
    name: department-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/txlcn-demo?characterEncoding=UTF-8&serverTimezone=UTC
    username: root

  mvc:
    throw-exception-if-no-handler-found: true # 出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8886/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

feign:
  hystrix:
    enabled: true # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
  client:
    config:
      default:
        connect-timeout: 300000
        read-timeout: 300000
      organization-server:
        connect-timeout: 300000
        read-timeout: 300000

security:
  oauth2:
#    client:
#      client-id: 123456
#      client-secret: 123456
    resource:
#      token-info-uri: http://localhost:8885/oauth/check_token #验证token 需要cilent_id和sclient_ecret
        user-info-uri: http://localhost:8885/oauth/user # 一个可以获取认证授权的自定义接口，可以在授权服务器，也可以在其他服务器上
        prefer-token-info: false # (是否使用token info，默认为true) 如果同时配置了token-info-uri 和 user-info-uri，这个属性设置使用哪个取验证授权

logging:
  level:
    root: info
    com:
      codingapi:
        txlcn: DEBUG







